### ISSUE TITLE
[Feature Request] OpenAI function call

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#187]
See https://platform.openai.com/docs/guides/gpt/function-calling.

**Comment by MorphlingEd** [comment]
have started working in branch `function_call` with basic examples

**Comment by dandansamax** [comment]
> have started working in branch `function_call` with basic examples

@MorphlingEd Thank you for noticing. The code looks amazing and the doc parser is so cool!

Just as an advision, do you think it is a good idea to move the "function call" to `ChatGPTConfig` class? Since we may want all kinds of agent to use outter API. Now the implementation is not so convenient to do that. Also, the "function call" performs as a config in openai API, so putting it in "config" part seems more clear.

**Comment by MorphlingEd** [comment]
> > have started working in branch `function_call` with basic examples
> 
> @MorphlingEd Thank you for noticing. The code looks amazing and the doc parser is so cool!
> 
> Just as an advision, do you think it is a good idea to move the "function call" to `ChatGPTConfig` class? Since we may want all kinds of agent to use outter API. Now the implementation is not so convenient to do that. Also, the "function call" performs as a config in openai API, so putting it in "config" part seems more clear.

Thanks for your comment. I am not sure whether I understand your meaning correctly but I assume what you mean is to make all agents able to do the job of function calling. I agree with that this may seem strange and inconvenient. That's because my original idea is not embodying this functionality in other agents. Instead I hope this one plays its role as an extra agent which takes the output of assistant as its input in role playing sessions. If it detects potential function calls it will execute and add the function execution results in natural language into the chat history (similar to the Observation in ReAct). If no function call is executed, it will mark the flag bool variable as False and will not add anything. 

Your reasoning makes sense. But `ChatGPTConfig` is a frozen data class, which makes customizing the function space hard and does not allow dynamically loading custom functions (though it may not be necessary?). On the other hand, if I only hope some agent to utilize part of the function space (e.g. making the User agent focus on thinking and making high-level plans but not calling functions), this becomes hard.

I do have something unclear in my mind. I think the key is to write a example of role-playing with function calling firstly. Otherwise I am not sure what is the best way to do this during the interaction.

**Comment by dandansamax** [comment]
> @dandansamax Thanks for your comment. I am not sure whether I understand your meaning correctly but I assume what you mean is to make all agents able to do the job of function calling. I agree with that this may seem strange and inconvenient. That's because my original idea is not embodying this functionality in other agents. Instead I hope this one plays its role as an extra agent which takes the output of assistant as its input in role playing sessions. If it detects potential function calls it will execute and add the function execution results in natural language into the chat history (similar to the Observation in ReAct). If no function call is executed, it will mark the flag bool variable as False and will not add anything.

I can get your thoughts and I agree this is a reasonable and "camel"-style solution. But I think this implementation may limit the power of "funcation call" functionality. Since passing message between agents may lose part of the information, directly allowing other agents to call functions may benefit them to gather information during "role playing".

Actually, I have a sceanario requiring this feature. Assuming we have an LLM (named Goriila) that can "search for other APIs through natural language". Now, I want an embodied agent to do some tasks by generating python codes. The embodied agent is able to call "Gorilla" API during generation to search for other APIs. Now the implementation is hard for me to do that.

You can keep the func agent in your design, but do you think it would be better if other agents can also use "function call"?

**Comment by dandansamax** [comment]
> Your reasoning makes sense. But ChatGPTConfig is a frozen data class, which makes customizing the function space hard and does not allow dynamically loading custom functions (though it may not be necessary?). On the other hand, if I only hope some agent to utilize part of the function space (e.g. making the User agent focus on thinking and making high-level plans but not calling functions), this becomes hard.

You are right. I think we can create another dataclass to represent "function call" API in low level. Or we can just remove `fronzen=True`. Feel free to call me by wechat if you want further discussion.
