### ISSUE TITLE
[BUG] About using role_playing_with_open_source_model.py base on local LLM(fastChat vicuna-7b-v1.5)

### ISSUE THREAD

**Issue by palinorz** [camel-ai/camel#415]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.1

### System information

3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] linux
0.1.1

### Problem description

hihi, firstly thanks for great work.

Following "Use Open-Source Models as Backends" chapter in https://github.com/camel-ai/camel, I have run a local LLM by fastChat（vicuna-7b-v1.5）.There are some problems when i use role_playing_with_open_source_model.py.
Chinese: 百忙之中打扰啦, 我们在本地机器上使用fastChat部署了一个vicuna-7b-v1.5, 当使用role_playing_with_open_source_model.py时候遇到了一些问题, 在微信群里进行了讨论后, 写了本issues反应遇到的情况和信息.

P.S. 
Files of vicuna-7b-v1.5 have been downloaded and put in /root/work_wujiewei/vicuna-7b-v1.5.
Server url of vicuna-7b-v1.5  has been publish at http://localhost:8000.

step1. I try to change the last 5 lines of role_playing_with_open_source_model.py as:
```
main(
    model_type=ModelType.VICUNA,
    model_path="/root/work_wujiewei/vicuna-7b-v1.5",
    server_url="http://localhost:8000",
)
```
terminal shows:
```
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```
snapshot:
![2](https://github.com/camel-ai/camel/assets/33821801/03304cf1-8a94-4f90-843a-a19caf775b64)

step2. Try to use a fake OpenAI Key, for example: export OPENAI_API_KEY=123456
terminal shows as:
```
ValueError: Invalid `model_path` (/root/work_wujiewei/vicuna-7b-v1.5) is provided. Tokenizer loading failed.
```
![3](https://github.com/camel-ai/camel/assets/33821801/f98a41ef-a441-492d-9948-1a9fee6f47c0)

step3. Try to change model_path in role_playing_with_open_source_model.py, from local path to huggingface path, like:
```
main(
    model_type=ModelType.VICUNA,
    model_path="lmsys/vicuna-7b-v1.5",
    server_url="http://localhost:8000",
)
```
terminal:
![4](https://github.com/camel-ai/camel/assets/33821801/75e354c3-832d-4b2f-a426-2cdb045b356d)

It seems the script try to connect huggingface, sadly, our server(centos7.9) cannot connect to huggingface directly you know.

----
If it is possible, hope we can load LLM file locally.
thanks very much.

### Reproducible example code

as uppon

**Comment by lightaime** [comment]
Hi @ocss884, are you interested in having a look into this issue?

**Comment by ocss884** [comment]
Hey @palinorz ! Thank you for choosing CAMEL!
Regarding your issue:

step 1: Yes an openai API key should be set since we are using their function
step 2: The `transformers` library cannot load the tokenizer stored in `/root/work_wujiewei/vicuna-7b-v1.5` properly due to the first error in the snapshot. It is not an issue of the `model_path`. An then, when you using `lmsys/vicuna-7b-v1.5`. As it is a HF repo name, the `AutoTokenizer` class trying to download tokenizer from huggingface.co that brings your step 3.

Could you provide the following information?
 - `torch` version
 - `transformers` version

Also, please make sure your model/tokenizer file doesn't broken. . I find an [issue](https://github.com/huggingface/transformers/issues/26897) with similar error message caused by network problem.
