### ISSUE TITLE
[Feature Request] Integrate Firecrawl

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#758]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Turn websites into LLM-ready data by using Firecrawl

**Comment by LysanderT** [comment]
Can I take on this?

**Comment by lightaime** [comment]
Thanks @LysanderT. That would be awesome! Here is their python sdk: https://docs.firecrawl.dev/sdks/python. 

A related PR is Jina reader integration here: https://github.com/camel-ai/camel/blob/master/camel/loaders/jina_url_reader.py

Let us know if you have any question during the integration!

**Comment by LysanderT** [comment]
@lightaime

I have several questions regarding Firecrawl, as it is quite different from Jina. Firecrawl provides two methods: scrape and crawl. The scrape method extracts data from a given URL, while the crawl method extracts data from the given URL and all its child URLs.

Given these differences, I'm unsure whether to unify these methods into a single method, similar to read_content in [jina_url_reader.py](https://github.com/camel-ai/camel/blob/master/camel/loaders/jina_url_reader.py?rgh-link-date=2024-07-29T17%3A00%3A49Z), or to maintain them as separate methods.

I lean towards having two separate methods because the optional parameters for each method are quite different, as detailed [here](https://docs.firecrawl.dev/api-reference/endpoint/scrape), and the return types differ based on my tests (one returns a dictionary and the other returns a list of dictionaries).

What do you think is the best approach?

**Comment by LysanderT** [comment]
i just created a draft PR... hope can get feedback soon

**Comment by Wendong-Fan** [comment]
> @lightaime
> 
> I have several questions regarding Firecrawl, as it is quite different from Jina. Firecrawl provides two methods: scrape and crawl. The scrape method extracts data from a given URL, while the crawl method extracts data from the given URL and all its child URLs.
> 
> Given these differences, I'm unsure whether to unify these methods into a single method, similar to read_content in [jina_url_reader.py](https://github.com/camel-ai/camel/blob/master/camel/loaders/jina_url_reader.py?rgh-link-date=2024-07-29T17%3A00%3A49Z), or to maintain them as separate methods.
> 
> I lean towards having two separate methods because the optional parameters for each method are quite different, as detailed [here](https://docs.firecrawl.dev/api-reference/endpoint/scrape), and the return types differ based on my tests (one returns a dictionary and the other returns a list of dictionaries).
> 
> Additionally, I think it's better to provide parameters when invoking the read methods, rather than upon initialization of the class as in Jina, since the two SDKs have different types of parameters.
> 
> What do you think is the best approach?

Hey @LysanderT , Thanks for the contribution! I agree with you that we should separate scrape and crawl

**Comment by Wendong-Fan** [comment]
> i just created a draft PR... hope can get feedback soon

Great! I've also made some progress on this issue. I'll do the review and we can merge our two PRs to create an even better solution.
